'use client'

import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import '@/app/_styles/globals.scss'
import Provider from './provider'
import { useAuth } from '@/hook/use-auth'
import AdminPanelLayout from '@/components/admin-panel/admin-panel-layout'
import { ContentLayout } from '@/components/admin-panel/content-layout'

// export const metadata = {
//   title: 'ISLA project',
//   description: 'Generated by create next app',
// }

function LayoutContent({ children }) {
  const { user, isAuth } = useAuth()

  if (!isAuth) {
    // 未登入時直接顯示內容，不包含側邊欄
    return <div className="min-h-screen">{children}</div>
  }

  // 已登入時顯示完整的管理面板佈局
  return (
    <AdminPanelLayout>
      <ContentLayout>
        <div className="p-6">{children}</div>
      </ContentLayout>
    </AdminPanelLayout>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant">
      <head>
        <title>ISLA Business</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Noto+Sans+TC:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <Provider>
        <body>
          <LayoutContent>{children}</LayoutContent>
          <ToastContainer />
        </body>
      </Provider>
    </html>
  )
}
