import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import '@/app/_styles/globals.scss'
import Provider from './provider'
import AdminPanelLayout from '@/components/admin-panel/admin-panel-layout'
import { ContentLayout } from '@/components/admin-panel/content-layout'

export const metadata = {
  title: 'ISLA project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Noto+Sans+TC:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <Provider>
        <body>
          {/* <Header /> */}
          <AdminPanelLayout>
            <ContentLayout title="ISLA 管理">
              <div className="p-6">
                <>{children}</>
              </div>
            </ContentLayout>
          </AdminPanelLayout>
          <ToastContainer />
        </body>
      </Provider>
    </html>
  )
}
