// import { Geist, Geist_Mono } from 'next/font/google'
import '@fontsource/plaster'
import '@fontsource/noto-sans-tc'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import Header from './_components/header/header'
import Footer from './_components/footer/footer'
import '@/app/_styles/globals.scss'
import Provider from './provider'
import Chat from './_components/service-chat/chat'

export const metadata = {
  title: 'ISLA project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Noto+Sans+TC:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <Provider>
        <body>
          <Header />
          <div style={{ marginTop: '80px' }}>{children}</div>
          <Footer />
          <ToastContainer />
          <Chat />
        </body>
      </Provider>
    </html>
  )
}
