// import { Geist, Geist_Mono } from 'next/font/google'
import '@fontsource/plaster'
import '@fontsource/noto-sans-tc'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import Header from './_components/header/header'
import Footer from './_components/footer/footer'
import '@/app/_styles/globals.scss'
import Provider from './provider'

export const metadata = {
  title: 'ISLA project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <Provider>
        <body>
          <Header />
          <ToastContainer
            position="top-right" // 放在畫面上方中間
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            toastClassName="custom-toast"
            style={{ marginTop: '70px', zIndex: 9999 }} // 根據 header 高度調整 marginTop
          />
          <div style={{ marginTop: '80px' }}>{children}</div>
          <Footer />
          {/* <ToastContainer /> */}
        </body>
      </Provider>
    </html>
  )
}
