// import { Geist, Geist_Mono } from 'next/font/google'
import '@fontsource/plaster'
import '@fontsource/noto-sans-tc'
import Header from './_components/header'
import Footer from './_components/footer'
import '@/app/_styles/globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
